# Generated by Django 3.0.5 on 2020-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlists',
            fields=[
                ('codename', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id_movie', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vote_count', models.IntegerField()),
                ('video', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=100)),
                ('adult', models.CharField(max_length=10)),
                ('backdrop_path', models.CharField(max_length=50, null=True)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=100, unique=True)),
                ('genre_ids', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overview', models.TextField(max_length=2000)),
                ('release_date', models.DateField()),
                ('code_list', models.ManyToManyField(blank=True, null=True, related_name='_movies_code_list_+', to='moviesapp.Watchlists')),
                ('genre', models.ManyToManyField(blank=True, null=True, related_name='_movies_genre_+', to='moviesapp.Genre')),
            ],
        ),
    ]
