# Generated by Django 3.0.5 on 2020-08-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='backdrop_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
